name: Jury Duty RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedgen
      
      - name: Run the jury duty script
        run: python jury-duty-rss.py > feed.xml

      - name: Deploy RSS feed to gh-pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch --all
          git checkout --orphan gh-pages
          git rm -rf .
          touch .nojekyll
          mv feed.xml index.xml
          git add .nojekyll index.xml
          git commit -m "Update RSS feed"
          git push origin gh-pages --force
