name: Jury Duty RSS Feed

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedgen
      
      - name: Run the jury duty script
        run: python jury-duty-rss.py > feed.xml

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push RSS feed to GitHub Pages
        run: |
          # Checkout gh-pages branch, create if it doesn't exist
          git checkout gh-pages || git checkout --orphan gh-pages

          # Remove all files from the previous push (but keep the RSS feed)
          git rm -rf .

          # Move feed.xml to index.xml
          mv feed.xml index.xml

          # Commit and push the file
          git add index.xml
          git commit -m "Update RSS feed"
          git push origin gh-pages --force

